<?php

declare(strict_types=1);

namespace App\Services\Auth;

use App\Models\User;
use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
use PragmaRX\Google2FA\Google2FA;

/**
 * TOTP enrolment and verification for the admin panel.
 *
 * Secrets and recovery codes are encrypted at rest by the User model's casts.
 * A secret is never considered active until the user has proved they can read
 * it back from their authenticator, so a mis-scanned QR code cannot lock
 * someone out of their own account.
 */
class TwoFactorService
{
    public function __construct(private readonly Google2FA $google2fa) {}

    /**
     * Begin enrolment: generate a secret and store it *unconfirmed*.
     */
    public function generateSecret(User $user): string
    {
        $secret = $this->google2fa->generateSecretKey();

        $user->forceFill([
            'two_factor_secret' => $secret,
            // Cleared so a re-enrolment cannot be confirmed by an old code.
            'two_factor_confirmed_at' => null,
            'two_factor_recovery_codes' => null,
        ])->save();

        return $secret;
    }

    /**
     * Complete enrolment once the user echoes back a valid code.
     *
     * @return list<string>|null the recovery codes, shown exactly once
     */
    public function confirm(User $user, string $code): ?array
    {
        if ($user->two_factor_secret === null || ! $this->verify($user, $code)) {
            return null;
        }

        $recoveryCodes = User::generateRecoveryCodes();

        $user->forceFill([
            'two_factor_confirmed_at' => now(),
            'two_factor_recovery_codes' => $recoveryCodes,
        ])->save();

        return $recoveryCodes;
    }

    /**
     * Verify a six-digit code.
     *
     * A one-window tolerance accepts the immediately preceding code, which
     * covers ordinary clock drift between the phone and the server without
     * meaningfully widening the window for an attacker.
     */
    public function verify(User $user, string $code): bool
    {
        $secret = $user->two_factor_secret;

        if ($secret === null) {
            return false;
        }

        $code = preg_replace('/\D/', '', $code) ?? '';

        if (strlen($code) !== 6) {
            return false;
        }

        return (bool) $this->google2fa->verifyKey($secret, $code, window: 1);
    }

    public function disable(User $user): void
    {
        $user->forceFill([
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null,
            'two_factor_confirmed_at' => null,
        ])->save();
    }

    /**
     * @return list<string>
     */
    public function regenerateRecoveryCodes(User $user): array
    {
        $codes = User::generateRecoveryCodes();

        $user->forceFill(['two_factor_recovery_codes' => $codes])->save();

        return $codes;
    }

    public function provisioningUri(User $user, string $secret): string
    {
        return $this->google2fa->getQRCodeUrl(
            (string) config('app.name'),
            $user->email,
            $secret,
        );
    }

    /**
     * QR code as inline SVG.
     *
     * SVG generated by the application is not the same thing as SVG accepted
     * from an upload — this markup is produced here, contains no script and no
     * external references, and never touches user input beyond the URI above.
     */
    public function qrCodeSvg(User $user, string $secret, int $size = 220): string
    {
        $writer = new Writer(new ImageRenderer(
            new RendererStyle($size, margin: 1),
            new SvgImageBackEnd,
        ));

        return $writer->writeString($this->provisioningUri($user, $secret));
    }
}
