<?php

declare(strict_types=1);

namespace App\Policies;

use App\Models\User;
use App\Support\Permissions;
use Illuminate\Database\Eloquent\Model;

/**
 * Maps the standard abilities onto the `{resource}.{ability}` permission names
 * generated by App\Support\Permissions.
 *
 * One base class rather than twenty hand-written policies, so a resource cannot
 * end up with a policy that disagrees with the permission matrix it was seeded
 * from. Super Admin never reaches here — a Gate::before rule short-circuits it.
 */
abstract class ResourcePolicy
{
    /**
     * The resource key in the permission matrix, e.g. 'products'.
     */
    abstract protected function resource(): string;

    public function viewAny(User $user): bool
    {
        return $this->allows($user, Permissions::VIEW_ANY);
    }

    public function view(User $user, Model $model): bool
    {
        return $this->allows($user, Permissions::VIEW);
    }

    public function create(User $user): bool
    {
        return $this->allows($user, Permissions::CREATE);
    }

    public function update(User $user, Model $model): bool
    {
        return $this->allows($user, Permissions::UPDATE);
    }

    public function delete(User $user, Model $model): bool
    {
        return $this->allows($user, Permissions::DELETE);
    }

    public function restore(User $user, Model $model): bool
    {
        return $this->allows($user, Permissions::DELETE);
    }

    public function forceDelete(User $user, Model $model): bool
    {
        // Permanent deletion is deliberately Super Admin only, which the
        // Gate::before rule grants and everyone else falls through to false.
        return false;
    }

    protected function allows(User $user, string $ability): bool
    {
        return $user->is_active
            && $user->hasPermissionTo(Permissions::name($this->resource(), $ability));
    }
}
