<x-layouts.admin-auth :title="__('admin.two_factor.setup_title')">
    <x-slot:subtitle>{{ __('admin.two_factor.setup_intro') }}</x-slot:subtitle>

    {{-- SVG generated by the application from a URI we build ourselves: it
         contains no script and no external references. This is not the same
         thing as accepting an SVG upload, which the media service refuses. --}}
    <div class="mb-5 flex justify-center rounded-md border border-border bg-white p-4">
        {!! $qrCode !!}
    </div>

    <p class="mb-2 text-caption text-text-muted">{{ __('admin.two_factor.manual_entry') }}</p>
    <p class="mb-6 rounded-md bg-surface-subtle px-3 py-2 text-center">
        <x-ui.measure :value="$secret" dir="ltr" />
    </p>

    <form method="POST" action="{{ route('admin.two-factor.setup.store') }}" class="flex flex-col gap-5">
        @csrf

        <x-ui.input
            name="code"
            :label="__('admin.two_factor.code')"
            :hint="__('admin.two_factor.code_hint')"
            required
            autocomplete="one-time-code"
            inputmode="numeric"
            autofocus
        />

        <x-ui.button type="submit" size="lg" full-width>{{ __('admin.two_factor.confirm') }}</x-ui.button>
    </form>
</x-layouts.admin-auth>
